export const mockUserData = [
  {
    id: 1,
    first_name: "Willi",
    last_name: "Caldwell",
    email: "wcaldwell0@yelp.com",
    institution: "Baghyatoolah Medical Sciences University",
  },
  {
    id: 2,
    first_name: "Jeralee",
    last_name: "Starkey",
    email: "jstarkey1@theguardian.com",
    institution: "Universidad Católica de Santiago de Guayaquil",
  },
  {
    id: 3,
    first_name: "Davon",
    last_name: "Dennison",
    email: "ddennison2@hubpages.com",
    institution: "Gazi University Ankara",
  },
  {
    id: 4,
    first_name: "Erminie",
    last_name: "Stollwerck",
    email: "estollwerck3@umn.edu",
    institution: "Chiba Institute of Technology",
  },
  {
    id: 5,
    first_name: "Ali",
    last_name: "Stear",
    email: "astear4@geocities.com",
    institution: "KDU College Sdn Bhd",
  },
  {
    id: 6,
    first_name: "Maitilde",
    last_name: "Shortt",
    email: "mshortt5@yellowbook.com",
    institution: "American University in Cairo",
  },
  {
    id: 7,
    first_name: "Karina",
    last_name: "Rawcliff",
    email: "krawcliff6@goo.ne.jp",
    institution: "Sindh Madressatul Islam University",
  },
  {
    id: 8,
    first_name: "Olivette",
    last_name: "McGow",
    email: "omcgow7@creativecommons.org",
    institution: "Delhi College of Engineering (DCE)",
  },
  {
    id: 9,
    first_name: "Berrie",
    last_name: "Elleton",
    email: "belleton8@t.co",
    institution: "Bangladesh Agricultural University",
  },
  {
    id: 10,
    first_name: "Batsheva",
    last_name: "Kemsley",
    email: "bkemsley9@google.it",
    institution: "Katowice School of Economics",
  },
];
